CUDA_VISIBLE_DEVICES=2 python run_ner.py \
    --dataset DuEE1.0 \
    --event_type role \
    --max_len 150 \
    --per_gpu_train_batch_size 64 \
    --num_train_epochs 30 \
    --per_gpu_eval_batch_size 48 \
    --gradient_accumulation_steps 1 \
    --model_name_or_path /data/qingyang/data/chinese-roberta-wwm-ext \
    --learning_rate 1e-5 \
    --linear_learning_rate 1e-5 \
    --early_stop 5 
